using AssistenciaTecnica.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

if (builder.Environment.IsDevelopment())
{
    builder.Services.AddDbContext<AppDbContext>(options =>
        options.UseSqlServer(
            builder.Configuration.GetConnectionString("DefaultConnection")));
}
else
{
    builder.Services.AddDbContext<AppDbContext>(options =>
        options.UseNpgsql(
            builder.Configuration.GetConnectionString("DefaultConnection")));
}

builder.Services.AddControllersWithViews();
builder.Services.AddSession();
builder.Services.AddHttpContextAccessor();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

    if (app.Environment.IsDevelopment())
    {
        db.Database.ExecuteSqlRaw(@"
            IF OBJECT_ID('Empresas', 'U') IS NULL
            BEGIN
                CREATE TABLE Empresas (
                    Id INT IDENTITY(1,1) PRIMARY KEY,
                    NomeEmpresa NVARCHAR(MAX) NOT NULL,
                    Usuario NVARCHAR(MAX) NOT NULL,
                    Senha NVARCHAR(MAX) NOT NULL,
                    WhatsApp NVARCHAR(MAX) NOT NULL DEFAULT '',
                    Ativo BIT NOT NULL DEFAULT 1,
                    DataCadastro DATETIME2 NOT NULL DEFAULT GETDATE()
                )
            END
        ");

        db.Database.ExecuteSqlRaw(@"
            IF COL_LENGTH('Configuracoes', 'EmpresaId') IS NULL
                ALTER TABLE Configuracoes ADD EmpresaId INT NOT NULL DEFAULT 1
        ");

        db.Database.ExecuteSqlRaw(@"
            IF COL_LENGTH('Clientes', 'EmpresaId') IS NULL
                ALTER TABLE Clientes ADD EmpresaId INT NOT NULL DEFAULT 1
        ");

        db.Database.ExecuteSqlRaw(@"
            IF COL_LENGTH('Servicos', 'EmpresaId') IS NULL
                ALTER TABLE Servicos ADD EmpresaId INT NOT NULL DEFAULT 1
        ");

        db.Database.ExecuteSqlRaw(@"
            IF COL_LENGTH('Servicos', 'Icone') IS NOT NULL
            BEGIN
                ALTER TABLE Servicos DROP COLUMN Icone
            END
        ");

        db.Database.ExecuteSqlRaw(@"
            IF COL_LENGTH('OrdensServico', 'EmpresaId') IS NULL
                ALTER TABLE OrdensServico ADD EmpresaId INT NOT NULL DEFAULT 1
        ");
    }
    else
    {
        db.Database.ExecuteSqlRaw(@"
            CREATE TABLE IF NOT EXISTS ""Empresas"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""NomeEmpresa"" text NOT NULL,
                ""Usuario"" text NOT NULL,
                ""Senha"" text NOT NULL,
                ""WhatsApp"" text NOT NULL DEFAULT '',
                ""Ativo"" boolean NOT NULL DEFAULT true,
                ""DataCadastro"" timestamp with time zone NOT NULL DEFAULT NOW()
            );
        ");

        db.Database.ExecuteSqlRaw(@"
            ALTER TABLE ""Configuracoes""
            ADD COLUMN IF NOT EXISTS ""EmpresaId"" integer NOT NULL DEFAULT 1;
        ");

        db.Database.ExecuteSqlRaw(@"
            ALTER TABLE ""Clientes""
            ADD COLUMN IF NOT EXISTS ""EmpresaId"" integer NOT NULL DEFAULT 1;
        ");

        db.Database.ExecuteSqlRaw(@"
            ALTER TABLE ""Servicos""
            ADD COLUMN IF NOT EXISTS ""EmpresaId"" integer NOT NULL DEFAULT 1;
        ");

        db.Database.ExecuteSqlRaw(@"
            ALTER TABLE ""Servicos""
            DROP COLUMN IF EXISTS ""Icone"";
        ");

        db.Database.ExecuteSqlRaw(@"
            ALTER TABLE ""OrdensServico""
            ADD COLUMN IF NOT EXISTS ""EmpresaId"" integer NOT NULL DEFAULT 1;
        ");
    }
}

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseSession();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Landing}/{id?}");

app.Run();