using AssistenciaTecnica.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// BANCO LOCAL = SQL SERVER
// RENDER = POSTGRESQL
if (builder.Environment.IsDevelopment())
{
    builder.Services.AddDbContext<AppDbContext>(options =>
        options.UseSqlServer(
            builder.Configuration.GetConnectionString("DefaultConnection")));
}
else
{
    builder.Services.AddDbContext<AppDbContext>(options =>
        options.UseNpgsql(
            builder.Configuration.GetConnectionString("DefaultConnection")));
}

builder.Services.AddControllersWithViews();
builder.Services.AddSession();

var app = builder.Build();

// CRIA A TABELA EMPRESAS NO RENDER SEM USAR MIGRATION ANTIGA
if (!app.Environment.IsDevelopment())
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

    db.Database.ExecuteSqlRaw(@"
        CREATE TABLE IF NOT EXISTS ""Empresas"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""NomeEmpresa"" text NOT NULL,
            ""Usuario"" text NOT NULL,
            ""Senha"" text NOT NULL,
            ""WhatsApp"" text NOT NULL DEFAULT '',
            ""Ativo"" boolean NOT NULL DEFAULT true,
            ""DataCadastro"" timestamp with time zone NOT NULL DEFAULT NOW()
        );
    ");
}

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseSession();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Landing}/{id?}");

app.Run();